name: Dreimannzelt
favicon: null
layout_spectrum: 0
typography_spectrum: 0.53883
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1d1d1d'
    - '#ffa858'
    - '#ffffff'
    - '#7c7c7c'
    - '#00b8d2'
  brandStrength: 0.75
  lightness: 0.25
  saturation: 0.875
  rhythmicContrast: 0.25
purpose: []
